version: "3"

services:

  php:
    image: carlostomazin/php-postfix:8.1-apache
    container_name: php
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    links:
      - db


  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pa


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80